# Use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.

#TLS context configuration

tls:
  keyPassword: "![e4kQX0QLXcj19lUEKWyziA==]"
  password: "![e4kQX0QLXcj19lUEKWyziA==]"
  
  
sftpvv:
  username: "![XA5Z3Pr7henNf1g0USrJtg==]"
  host: "![P4/84/r4cQtjgOVuvoQLZZrQmVqeE8KHZuNXRRvEEM8=]"
  password: "![mS/a9VuxLjazv/YzXZpGoQ==]"
  

sftpblume: 
  username: "![oidJYsVC4BcnF4QtnBqtzQ==]"
  host: "![F+pYkmzeXoiQxnR7Dt7vmtHt5t+K5d6Hscwp1B1fZbA=]"
  password: "![YSGEDF2WM96elYKIt8j7fQ==]"
  
