[
  {
    "shipmentNumber": "VALR20230420000001",
    "Origin Port (UNLOCODE)": "",
    "Destination Port (UNLOCODE)": "",
    "Customer": "OEC Group",
    "scheduledPickupDate": "4/30/2023 9:00",
    "scheduledDeliveryDate": "",
    "Ocean Carrier": "ONE",
    "VesselName": "ONE Majesty",
    "Origin Name/Terminal": "YUSEN TERMINAL",
    "Origin Address": "701 NEWDOCK AVE.",
    "Origin City": "Terminal Island",
    "Origin State": "CA",
    "Origin Postal Code": "90731",
    "Origin Country": "United States",
    "Final Destination Name": "Little Giant Ladder Systems, LLC",
    "Final Destination Address": "1198 N Spring Creek Place",
    "Final Destination City": "Springville",
    "Final Destination State": "UT",
    "Final Destination Postal Code": "84664",
    "Final Destination Country": "United States",
    "commodityClass": "FAK",
    "commodityGoodsNum": "4611110",
    "EquipmentType": "40HC",
    "equipmentNumber": "KOCU4249600",
    "grossWeight": "6373",
    "netWeight": "6373",
    "weightUOM": "KG",
    "Pieces": "324",
    "Seal": "213198358",
    "Booking Number": "",
    "Bill of Lading": "HDMUSHAZ86326100",
    "VV_Invoice_No__Import": "GOFOI2300953",
    "PackageType": "TOTAL_LOAD",
    "FreightDescription": "FAK",
    "Volume": "20",
    "VolumeUOM": "MTQ",
    "Voyage Number": "008E",
    "Planned Vessel Departure": "",
    "Shipment Type": "Import",
    "BCO Name": "Little Giant Ladder Systems, LLC",
    "Ocean Carrier SCAC": "ONEY",
    "Cut-off Date": "",
    "Documentation Cut-off Date": ""
  },
  {
    "shipmentNumber": "VALR20230420000002",
    "Origin Port (UNLOCODE)": "",
    "Destination Port (UNLOCODE)": "",
    "Customer": "OEC Group",
    "scheduledPickupDate": "4/25/2023 7:00",
    "scheduledDeliveryDate": "",
    "Ocean Carrier": "CMA CGM",
    "VesselName": "WAN HAI A08",
    "Origin Name/Terminal": "PACIFIC MARINE SERVICES",
    "Origin Address": "1521 PIER J AVE",
    "Origin City": "Long Beach",
    "Origin State": "CA",
    "Origin Postal Code": "90802",
    "Origin Country": "United States",
    "Final Destination Name": "Aligned Logistics",
    "Final Destination Address": "720 Gladiola St, STE C",
    "Final Destination City": "Salt Lake City",
    "Final Destination State": "UT",
    "Final Destination Postal Code": "84104",
    "Final Destination Country": "United States",
    "commodityClass": "FAK",
    "commodityGoodsNum": "4611110",
    "EquipmentType": "40ST",
    "equipmentNumber": "HMMU6461442",
    "grossWeight": "7039",
    "netWeight": "7039",
    "weightUOM": "KG",
    "Pieces": "845",
    "Seal": "213195324",
    "Booking Number": "",
    "Bill of Lading": "HDMUSHAZ86326100",
    "VV_Invoice_No__Import": "GOFOI2300953",
    "PackageType": "TOTAL_LOAD",
    "FreightDescription": "FAK",
    "Volume": "20",
    "VolumeUOM": "MTQ",
    "Voyage Number": "E002",
    "Planned Vessel Departure": "",
    "Shipment Type": "Import",
    "BCO Name": "Aligned Logistics",
    "Ocean Carrier SCAC": "CMDU",
    "Cut-off Date": "",
    "Documentation Cut-off Date": ""
  },
  {
    "shipmentNumber": "VALR20230420000003",
    "Origin Port (UNLOCODE)": "",
    "Destination Port (UNLOCODE)": "",
    "Customer": "DB Schenker",
    "scheduledPickupDate": "4/27/2023 4:00",
    "scheduledDeliveryDate": "",
    "Ocean Carrier": "Hyundai Line",
    "VesselName": "NYK Meteor",
    "Origin Name/Terminal": "NSE Products Inc",
    "Origin Address": "275 E 1325 S",
    "Origin City": "Provo",
    "Origin State": "UT",
    "Origin Postal Code": "84606",
    "Origin Country": "United States",
    "Final Destination Name": "Yusen Terminals Inc",
    "Final Destination Address": "701 New Dock St",
    "Final Destination City": "Terminal Island",
    "Final Destination State": "CA",
    "Final Destination Postal Code": "90731",
    "Final Destination Country": "United States",
    "commodityClass": "FAK",
    "commodityGoodsNum": "4611110",
    "EquipmentType": "20HC",
    "equipmentNumber": "TLLU4358318",
    "grossWeight": "9272",
    "netWeight": "9272",
    "weightUOM": "KG",
    "Pieces": "21",
    "Seal": "",
    "Booking Number": "66525274",
    "Bill of Lading": "",
    "VV_Invoice_No__Import": "66525274",
    "PackageType": "TOTAL_LOAD",
    "FreightDescription": "FAK",
    "Volume": "40",
    "VolumeUOM": "MTQ",
    "Voyage Number": "074E",
    "Planned Vessel Departure": "",
    "Shipment Type": "Export",
    "BCO Name": "NSE Products",
    "Ocean Carrier SCAC": "HDMU",
    "Cut-off Date": "5/10/2023 0:00",
    "Documentation Cut-off Date": "5/9/2023 12:00"
  },
  {
    "shipmentNumber": "VALR20230420000004",
    "Origin Port (UNLOCODE)": "",
    "Destination Port (UNLOCODE)": "",
    "Customer": "DB Schenker",
    "scheduledPickupDate": "4/29/2023 2:00",
    "scheduledDeliveryDate": "",
    "Ocean Carrier": "Mediterranean Shipping Company",
    "VesselName": "NYK Meteor",
    "Origin Name/Terminal": "NSE Products Inc",
    "Origin Address": "275 E 1325 S",
    "Origin City": "Provo",
    "Origin State": "UT",
    "Origin Postal Code": "84606",
    "Origin Country": "United States",
    "Final Destination Name": "Yusen Terminals Inc",
    "Final Destination Address": "701 New Dock St",
    "Final Destination City": "Terminal Island",
    "Final Destination State": "CA",
    "Final Destination Postal Code": "90731",
    "Final Destination Country": "United States",
    "commodityClass": "FAK",
    "commodityGoodsNum": "4611110",
    "EquipmentType": "40ST",
    "equipmentNumber": "CMAU6733519",
    "grossWeight": "9272",
    "netWeight": "9272",
    "weightUOM": "KG",
    "Pieces": "27",
    "Seal": "",
    "Booking Number": "66525274",
    "Bill of Lading": "",
    "VV_Invoice_No__Import": "66525274",
    "PackageType": "TOTAL_LOAD",
    "FreightDescription": "FAK",
    "Volume": "40",
    "VolumeUOM": "MTQ",
    "Voyage Number": "074E",
    "Planned Vessel Departure": "",
    "Shipment Type": "Export",
    "BCO Name": "NSE Products",
    "Ocean Carrier SCAC": "MSCU",
    "Cut-off Date": "6/12/2023 0:00",
    "Documentation Cut-off Date": "6/11/2023 12:00"
  },
  {
    "shipmentNumber": "F048099424",
    "Origin Port (UNLOCODE)": "",
    "Destination Port (UNLOCODE)": "",
    "Customer": "Expeditors",
    "scheduledPickupDate": "3/7/2023 7:00",
    "scheduledDeliveryDate": "",
    "Ocean Carrier": "Hapag Lloyd Container Line",
    "VesselName": "",
    "Origin Name/Terminal": "TRAPAC LOS ANGELES",
    "Origin Address": "630 WEST HARRY BRIDGES BOULEVARD",
    "Origin City": "Wilmington",
    "Origin State": "CA",
    "Origin Postal Code": "90744",
    "Origin Country": "United States",
    "Final Destination Name": "BUTLER INTERMODAL TERMINAL-VALOR VI",
    "Final Destination Address": "30835 220TH ST",
    "Final Destination City": "Shell Rock",
    "Final Destination State": "IA",
    "Final Destination Postal Code": "50670",
    "Final Destination Country": "United States",
    "commodityClass": "FAK",
    "commodityGoodsNum": "4611110",
    "EquipmentType": "40HC",
    "equipmentNumber": "BMOU5537334",
    "grossWeight": "18642",
    "netWeight": "18642",
    "weightUOM": "KG",
    "Pieces": "9",
    "Seal": "HLG432885",
    "Booking Number": "",
    "Bill of Lading": "HLCUTA12206BAAW3",
    "VV_Invoice_No__Import": "F048099242",
    "PackageType": "TOTAL_LOAD",
    "FreightDescription": "FAK",
    "Volume": "10",
    "VolumeUOM": "MTQ",
    "Voyage Number": "",
    "Planned Vessel Departure": "",
    "Shipment Type": "Import",
    "BCO Name": "John Deere",
    "Ocean Carrier SCAC": "HLCU",
    "Cut-off Date": "",
    "Documentation Cut-off Date": ""
  },
  {
    "shipmentNumber": "F047449568",
    "Origin Port (UNLOCODE)": "",
    "Destination Port (UNLOCODE)": "",
    "Customer": "Expeditors",
    "scheduledPickupDate": "1/24/2022 7:00",
    "scheduledDeliveryDate": "",
    "Ocean Carrier": "Hamburg Sud",
    "VesselName": "",
    "Origin Name/Terminal": "BUTLER INTERMODAL TERMINAL-VALOR VI",
    "Origin Address": "30835 220TH ST",
    "Origin City": "Shell Rock",
    "Origin State": "IA",
    "Origin Postal Code": "50670",
    "Origin Country": "United States",
    "Final Destination Name": "SSA Terminals LLC",
    "Final Destination Address": "700 Pier A Plaza",
    "Final Destination City": "Long Beach",
    "Final Destination State": "CA",
    "Final Destination Postal Code": "90813",
    "Final Destination Country": "United States",
    "commodityClass": "FAK",
    "commodityGoodsNum": "4611110",
    "EquipmentType": "40HC",
    "equipmentNumber": "MRSU4813860",
    "grossWeight": "3822.5",
    "netWeight": "3822.5",
    "weightUOM": "KG",
    "Pieces": "5",
    "Seal": "238364",
    "Booking Number": "1CHI012833",
    "Bill of Lading": "",
    "VV_Invoice_No__Import": "F047449568",
    "PackageType": "TOTAL_LOAD",
    "FreightDescription": "FAK",
    "Volume": "10",
    "VolumeUOM": "MTQ",
    "Voyage Number": "",
    "Planned Vessel Departure": "",
    "Shipment Type": "Export",
    "BCO Name": "John Deere",
    "Ocean Carrier SCAC": "SUDU",
    "Cut-off Date": "25/5/2023  4:00",
    "Documentation Cut-off Date": "24/5/2023  4:00"
  }
]